
tasks:
  - command: |
      chmod 600 ~/.ssh/id_rsa
      chmod 644 ~/.ssh/id_rsa.pub
      ssh-keyscan github.com >> ~/.ssh/known_hosts
      
  - command: |
      git remote set-url origin git@github.com:Sneha013084/Sneha013084-pep-spring-project.git
      dos2unix commit-command.sh || sed -i 's/\r$//' commit-command.sh
      bash commit-command.sh
